products = [
    {"name": "apple", "keeps_days": 10, "buy": 0.1, "sell": 0.7, "order_size": 200},
    {
        "name": "toothpaste",
        "keeps_days": 365,
        "buy": 1.80,
        "sell": 2.30,
        "order_size": 100,
    },
    {"name": "carrot", "keeps_days": 14, "buy": 0.4, "sell": 1, "order_size": 200},
    {"name": "avocado", "keeps_days": 6, "buy": 1, "sell": 1.20, "order_size": 150},
    {"name": "toilet paper", "keeps_days": 365, "buy": 2, "sell": 4, "order_size": 100},
    {
        "name": "salmon",
        "keeps_days": 4,
        "buy": 1.7,
        "sell": 4,
        "last_day_discount": True,
        "order_size": 50,
    },
    {
        "name": "quinoa salad",
        "keeps_days": 4,
        "buy": 2.3,
        "sell": 4.5,
        "last_day_discount": True,
        "order_size": 50,
    },
    {
        "name": "frozen pizza",
        "keeps_days": 150,
        "buy": 0.7,
        "sell": 2.5,
        "order_size": 100,
    },
    {"name": "cola", "keeps_days": 365, "buy": 0.7, "sell": 2.5, "order_size": 200},
    {
        "name": "croissant",
        "keeps_days": 1,
        "buy": 0.7,
        "sell": 1,
        "last_hour_discount": True,
        "order_size": 50,
    },
    {
        "name": "bread",
        "keeps_days": 1,
        "buy": 0.4,
        "sell": 1.2,
        "last_hour_discount": True,
        "order_size": 50,
    },
]
